site_name: Selene
site_url: https://hotenov.github.io/selene-with-docs/

nav:
- Selene: "index.md"
- Contributing: "CONTRIBUTING.md"
- Release Process: "CONTRIBUTING/#release-process"
- Changelog: "CHANGELOG.md"
- License: "LICENSE.md"
- "Guides":
  - "Docs Setup": "guides/docs-setup.md"
- About: "about.md"

theme:
  name: material
  favicon: img/favicon.ico
  logo: img/apple-touch-icon.png
  custom_dir: docs/overrides
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: indigo
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to light mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: blue grey
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to dark mode
  features:
  - search.suggest
  - search.highlight
  - content.tabs.link

plugins:
- search
- autorefs
- mkdocstrings

markdown_extensions:
  - pymdownx.snippets:
      # base_path: ["."]  # for root of repo
      base_path: ["docs"]
